[package]
name = "rdyn-plugins-macros"
version = "0.1.0"
edition = "2021"
authors = ["zephhhhhh"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"

rdyn-plugins = { path = "../rdyn-plugins" }